### ISSUE TITLE
YAML - assign non-used entries with null (impedance Notebook)

### ISSUE THREAD

**Issue by vwvbrand** [AD4GD/pilot-2#9]
For the configuration file with ecological parameters of impedance, it is suggested to automatically assign non-used parameters with 'null'
For example, the current YAML block
```
vrt_railways:
  decline_type: exp_decline
  enabled: true
  exp_decline:
    lambda_decay: 200
  prop_decline:
    k: 10
```
should turn into:
```
vrt_railways:
  decline_type: exp_decline
  enabled: true
  exp_decline:
    lambda_decay: 200
  prop_decline:
    k: null
```

, if user chooses 'decline_type'.

It will improve the readability of YAML file and filter out non-required parameters for user because only one value is required - either lambda_decay or k_value.
